# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastlite_dataclass_default_functional',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/fastlite_dataclass_default_functional',
                'lib_path': 'fastlite_dataclass_default_functional'},
  'syms': { 'fastlite_dataclass_default_functional.core': { 'fastlite_dataclass_default_functional.core.foo': ( 'core.html#foo',
                                                                                                                'fastlite_dataclass_default_functional/core.py')}}}
